# Generated by Django 3.2.3 on 2021-07-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id pago')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('contrasena', models.CharField(max_length=9, verbose_name='contraseña')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pago')),
            ],
        ),
    ]
